### ISSUE TITLE
Publish Gumroad products

### ISSUE THREAD

**Issue by ElviraEulitz** [ruha-healing/ruha-healing.github.io#9]
2 Gumroad products until the end of 2020 available:

1) Monthly membership - 19€
2) Card of 10 - 35€

**Comment by cburgdorf** [comment]
For reference, what's the name of the competitor product you might end up using?

**Comment by ElviraEulitz** [comment]
Use of Fitogram Pro instead of Gumroad. Products are available on the website now.
